### ISSUE TITLE
Show normal and gzipped sizes together

### ISSUE THREAD

**Issue by frenzzy** [sindresorhus/gulp-size#12]
[gulp] gulp-size: app.css 3.38 kB
[gulp] gulp-size: app.css 1.32 kB (gzipped)
=>
[gulp] gulp-size: app.js 3.38 kB (1.32 kB gzipped)

**Comment by stevenvachon** [comment]
I agree with showing both.

**Comment by meefox** [comment]
+1 for displaying both
