### ISSUE TITLE
Get the size value

### ISSUE THREAD

**Issue by VladShcherbin** [sindresorhus/gulp-size#20]
Hello, how can I get the size value ? 
E.g. output with gulp-notify. Smth like size().value.

Is it possible ?

**Comment by sindresorhus** [comment]
Do you want the size of individual files or total?

**Comment by VladShcherbin** [comment]
The total value.
I compile sass, concat js files and have a notification after it is done. So, I wanted to add a string with the size of the output file to the notification in order not to open the terminal. Is it possible somehow?

**Comment by VladShcherbin** [comment]
can you please confirm it is working

my gulp
```
gulp.task('test', function () {
	var s = size();
	gulp.src('test.js')
		.pipe(s)
		.pipe(gulp.dest('dist'))
		.pipe(notify({
			onLast: true,
			message: 'Total file size ' + s.prettySize
		}));
});
```
and the output is undefined
```
Using gulpfile ~/Sites/test/gulpfile.js
Starting 'test'...
Finished 'test' after 24 ms
all files 34 B
gulp-notify: [Gulp notification] Total file size undefined
```

**Comment by sindresorhus** [comment]
Sorry, did a mistake in the example. Fixed in https://github.com/sindresorhus/gulp-size/commit/6db66e94d81be250ec4e5bf4c22b684c30a2b6bd

**Comment by VladShcherbin** [comment]
Yes, works like a charm now.
The response and the fixes are blazingly fast, you is awesome, thank you for your work!

**Comment by dvLden** [comment]
What a coincidence, googled this issue and after almost 1 year this seems to be an issue again.

`size().size` => `undefined`
`size().prettySize` => `undefined`

`var s = size();`
`s.size` => `undefined`
`s.prettySize` => `undefined`
