### ISSUE TITLE
Why is title automatically quoted?

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/gulp-size#25]
Can [this line](https://github.com/sindresorhus/gulp-size/blob/master/index.js#L9)

	title = title ? ('\'' + chalk.cyan(title) + '\' ') : '';

be replaced with this one?

	title = title ? chalk.cyan(title) : '';

**Comment by sindresorhus** [comment]
I think I did it so it's clear what's what when colors are not supported. Not sure whether that makes sense though.

**Comment by bfred-it** [comment]
It does make sense… but it's also a bit annoying when you don't want that. For now I got around it by overriding the logging utility.

**Comment by sindresorhus** [comment]
If you care enough do a PR removing the quotes, I'll accept.

**Comment by bfred-it** [comment]
Cool! I'll do in half a day, hopefully.
