### ISSUE TITLE
Show filename and size instead of total (when piping one file)

### ISSUE THREAD

**Issue by smhg** [sindresorhus/gulp-size#3]
I'm using `gulp-size` _after_ browserify and less because I am interested in the total filesize. Since my pipes build multiple files, having only the total doesn't tell me _which file_ has which size.
I can add `showFiles`, but in that case I have 2 lines for each output file.

What do you think about adding an option `showTotal` to turn totals off? Or is there a way to figure out only one file is piped and replace 'total' by the filename?

I'm happy to send a PR after your feedback.

(As a tiny sidenote: the blue used on the filename is the only color that is unreadable on Windows - would cyan be an option? A color option would be overkill I guess.)

**Comment by NickTomlin** [comment]
@smhg 

I'm running into the same issue, did you end up finding a fix for this?

**Comment by smhg** [comment]
I don't remember, sorry. I abandoned gulp in favor of a custom build script.
