### ISSUE TITLE
showFiles: true unreadable on putty ?

### ISSUE THREAD

**Issue by toplefty** [sindresorhus/gulp-size#30]
Sorry that issue not totally related with gulp-size. With Putty client, on individual file names, the dark blue color is close to absolutely unreadable on black background. I guess I can modify the color in my own putty settings, but maybe you'd want to modify it to a color natively readable for putty users (lighter blue).

**Comment by sindresorhus** [comment]
That should already be happening with the latest version as it uses Chalk for coloring which uses light-blue on Windows. https://github.com/chalk/chalk/blob/master/index.js#L8 Unless of course your terminal identifies itself as `xterm`.
