### ISSUE TITLE
Unable to retrieve size of total files for gulp-notify / size().prettySize, size().size

### ISSUE THREAD

**Issue by dvLden** [sindresorhus/gulp-size#33]
Well basically same issue that was opened almost 1 year ago.

https://github.com/sindresorhus/gulp-size/issues/20

**Comment by sindresorhus** [comment]
Tests disagrees: https://github.com/sindresorhus/gulp-size/blob/b2632368a7bf75cde538f0162d38196cd2927613/test.js#L121-L122

**Comment by dvLden** [comment]
Is there any way that I can track down the issue, because this is what it is shown back to me...
![Uploading Screen Shot 2016-01-02 at 04.52.13.png…]()

**Comment by edphn** [comment]
Same issue here. The problem occurs when I'm trying to display prettySize in gulp-notify. In console everything works fine.

**Comment by vovayatsyuk** [comment]
1. Make sure you are using `gulp-size` and not `gulp-filesize` package. (It was my mistake)
2. Make sure that `onLast` option is set to `true`.
3. Make sure you are using a `function` for message in notify options, and call for `s.prettySize` inside of it.
4. Don't forget to call `.pipe(s)`

Example:

```js
.pipe(s)
.pipe(notify({
    onLast: true,
    message: function () {
        return 'See <%= file.relative %> ' + s.prettySize;
    }
}));
```

**Comment by edphn** [comment]
@vovayatsyuk Thank you. Works like a charm right now.

**Comment by dvLden** [comment]
I have decided yesterday to rewrite my gulp tasks and change structure... I couldn't get notify to work at all, but size did work this time in console output.

So I tried to pipe `gulp-size` and then `gulp-notify` and then the `gulp.dest` and in this order everything works as suppoused.

It did not work before at all, because I had size and notify right after destination.
