### ISSUE TITLE
Error when using `{gzip: true}`

### ISSUE THREAD

**Issue by sjmiles** [sindresorhus/gulp-size#35]
zlib.js:166
    callback(null, buf);
    ^
TypeError: object is not a function
    at Gzip.onEnd (zlib.js:166:5)
    at Gzip.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by sindresorhus** [comment]
Upgrade Node.js.

https://github.com/sindresorhus/gulp-size/blob/1303830e9fc48e5f6787ddbfee232f1d956b2e35/package.json#L13

**Comment by sjmiles** [comment]
Thanks, sorry for the noise.
