### ISSUE TITLE
Don't log output.

### ISSUE THREAD

**Issue by lukasoppermann** [sindresorhus/gulp-size#37]
Hey @sindresorhus,

I would love to have an an option like `hideLog: true` which just does not output anything.

It would be extremely simple to implement and allow for one to collect different size measurements and report a result in the end.

I am happy to send PR if you want, its basically just another check in the if that otherwise reports `all`. There should be no bc problem.

**Comment by sindresorhus** [comment]
Can you share your specific use-case? (I'm asking as there might be a better way to solve the problem)

**Comment by lukasoppermann** [comment]
Well, my specific use-case is that I want to report an overall improvement (in %) for which I need the size at specific points in the execution. However I do not want my output to be littered with reported sizes, as this makes it harder to scan and find what you are looking for.

**Comment by sindresorhus** [comment]
I would be ok with a `silent` option if it came as a pull request with a test and readme updates.

**Comment by lukasoppermann** [comment]
Hey, I wrote the change, but when adding the readme I notice that setting `showTotal` to false, does the same thing, so this is actually not needed.

However, **FYI** I noticed that `npm test` fails due to formatting issues. Maybe you want to look into this.
