### ISSUE TITLE
gziped and non gziped log

### ISSUE THREAD

**Issue by meefox** [sindresorhus/gulp-size#38]
Could you add possibility to see gziped and non gziped size at the same time.
Thank you.

**Comment by sindresorhus** [comment]
Why? I have yet to receive a good argument for it.

https://github.com/sindresorhus/gulp-size/issues/12

**Comment by meefox** [comment]
This task is very useful for resources optimization work.
I have shared resources which is using by online(gzip) web-app and as offline phone app (non gzip).
So it would be useful to see progress for both.

**Comment by benjibee** [comment]
I actually saw #12 and thought the same: why would anyone need both? Now I have an Electron app and web app built from the same resources and have to keep track of compressed / non-compressed file sizes. So yeah, I think @meefox has exactly the argument you're looking for @sindresorhus!

**Comment by Munter** [comment]
gzipped size is relevant for network performance while unzipped size is relevant for parse time performance. Both are relevant at the same time

**Comment by sindresorhus** [comment]
Alright. Thanks for sharing some valid use-cases. PR welcome then :)

**Comment by orditeck** [comment]
I made a workaround that works for my intended use, thought it may help someone:

```
function scss() {
    const s = size({ showTotal: false });
    const sgzipped = size({ showTotal: false, gzip: true });

    return gulp.src('./assets/sass/styles.scss')
        .pipe(sass())
        .pipe(concat('style.css'))
        .pipe(s).pipe(sgzipped)
        .pipe(gulp.dest('./'))
        .on('end', () => log(`Done building ${colors.magenta(`'style.css'`)}. (${s.prettySize} / ${sgzipped.prettySize} gzipped)`));
}
```

**Comment by martinBadin** [comment]
I using

```js
gulp
    .src(/* sources */)
    .pipe(process.env.NODE_ENV !== 'production' ? sourcemaps.init() : noop())
    .pipe(sass().on('error', sass.logError))
    .pipe(postcss())
    .pipe(concat('style.min.css'))
    .pipe(
      process.env.NODE_ENV !== 'production' ? sourcemaps.write('.') : noop()
    )
    .pipe(size({gzip: process.env.NODE_ENV === 'production'}))
    .pipe(gulp.dest(/* output */))
```

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/gulp-size/commit/e5200f1a01235ca936064351b409dec4566f03ed.
