### ISSUE TITLE
Why are some files lost when I use your plugin?

### ISSUE THREAD

**Issue by s-belichenko-sold** [sindresorhus/gulp-size#41]
My simple task:
```
gulp.task('images', () => {
    gulp.src('app/images/**/*')
        .pipe(gulp.dest('dist/images'))
        .pipe($.size({title: 'images', showFiles}))
});
```
If I run this task on a large number of files (46 or more), then this task does not process all files. They are not even copied to the `dist` folder.

**Comment by sindresorhus** [comment]
Gulp plugins must be before `gulp.dest` as Gulp plugins are transform streams and must be piped to a writable stream. In your case here, you're not doing that, so when the buffer is full (45 files), it finishes.
