### ISSUE TITLE
full file path

### ISSUE THREAD

**Issue by mikestreety** [sindresorhus/gulp-size#44]
Hi!

Thank you so much for this excellent plugin.

I was wondering if it is possible to output the whole path of the file, not just the file name? Due to our folder structure we have a lot of files with the same name in a project, identified by their folders.

I have edited my local version by changing [this line](https://github.com/sindresorhus/gulp-size/blob/master/index.js#L41) to `file.path` - however this outputs the file path from the root of the server, I was expecting one relative to the `gulpfile`.

Thanks again 👍

**Comment by sindresorhus** [comment]
The plugin outputs files relative to your `base`. It uses `file.relative` => https://github.com/gulpjs/vinyl#filerelative I'm not sure what you've set your `cwd` and `base` to, but that affects it.

**Comment by mikestreety** [comment]
Thanks for the prompt reply. Will have a dig through my gulpfile and work where that is being set /how I can override it.

P.s. Thanks for everything you do for Gulp & all the other open source projects you have 🙌 👍
