### ISSUE TITLE
Total size project

### ISSUE THREAD

**Issue by brendan8c** [sindresorhus/gulp-size#48]
The total size of the project can be calculated without using "gulp-notify"..
(Useful for, for example, reporting the total project size with gulp-notify)

```
const build = 'build/'
const config_size = {
    showTotal: true,
    pretty: true,
    title: 'All project: '
}
function allSize() {
    return src(build + '**/*.*')
        .pipe(size(config_size))
}
exports.allSize = allSize // gulp allSize
```

In my build, this works great!

**Comment by sindresorhus** [comment]
Is this a question or statement? It's not really clear what you're trying to say.

**Comment by sindresorhus** [comment]
> The total size of the project can be calculated without using "gulp-notify"..

Nowhere in the docs does it say you have to use `gulp-notify`.

**Comment by brendan8c** [comment]
This statement )
![2021-05-31 08_27_02-Total size project · Issue #48 · sindresorhus_gulp-size](https://user-images.githubusercontent.com/61526280/120144162-20b25c00-c1ea-11eb-92a5-1b87d5f977e5.png)
I thought that this means that I need to use gulp-notify

**Comment by sindresorhus** [comment]
It's just an example, per the "for example" wording.
